export const INCOMING_MESSAGE_TYPES = {
    IS_DARK_MODE: 'IS_DARK_MODE',
    IS_USER_LOGGED_IN: 'IS_USER_LOGGED_IN',
};

export const OUTGOING_MESSAGE_TYPES = {
    EXPO_PUSH_TOKEN: 'EXPO_PUSH_TOKEN',
};

export const URI = 'http://192.168.1.79:3000';
